### PR TITLE
Update to vtk > 6 version

### PR DESCRIPTION
**Pull request by brunoeducsantos**
Hi,
Thanks for the amazing implementation. I notice getting connection to vtk is not updated according to new API, I change that.
Regards,
Bruno

### CODE REVIEW

**Comment by rspezialetti** [comment]
Hi,
thanks for the update of VTK version. I suggest you to update also the required version of VTK in the CMakeLists.txt. As regards the parallel calculation of the descriptors. I tried to run the updated code but it fails with a segmentation error. Did it worked for you ?

**Comment by rspezialetti** [comment]
Hi Bruno, why did you close the pull request?

**Comment by brunoeducsantos** [comment]
Hi ,
Sorry. For the confusion. 
I delete my forked version because I thought my changes won't be applied anymore. Now, I don't know how to deal with it.
So, I will create a new pull request.
 Thanks,
Bruno

**Comment by rspezialetti** [comment]
Hi,
no problem. 
Could you also add the change to the new required VTK version in the CMakeList.txt ?

**Pull request closed without merging**
