### PR TITLE
change vtk inputdata to new version

### PR DESCRIPTION
**Pull request by brunoeducsantos**

### CODE REVIEW

**Comment by brunoeducsantos** [comment]
Is it working for you @rspezialetti ?

**Comment by rspezialetti** [comment]
@brunoeducsantos , I had to comment  the `include(${VTK_USE_FILE})` on src/CMakeList.txt to make it working. I'm testing the code on Ubuntu, which platform do you use?

**Comment by brunoeducsantos** [comment]
@rspezialetti I am using Ubuntu as well

**Comment by rspezialetti** [comment]
is it working for you with the ` include(${VTK_USE_FILE})` ?

**Comment by brunoeducsantos** [comment]
Yes. It does not work without it.

**Comment by rspezialetti** [comment]
Ok, which version of VTK are you using ?

**Comment by brunoeducsantos** [comment]
I am using version 6.2

**Comment by rspezialetti** [comment]
I'm using VTK 8.0. As you can see on the VTK tutorial, the new version of VTK does not need to use the include. Could you add this piece of code?
Thanks!

```
if (VTK_VERSION VERSION_LESS "8.90.0")
  # old system
  include(${VTK_USE_FILE})
```

**Comment by brunoeducsantos** [comment]
@rspezialetti  changes applied. Let me know what do you think.

**Comment by rspezialetti** [comment]
@brunoeducsantos, please just add this line `endif()`to close the if. It works like a charm. Thank you!

**Comment by brunoeducsantos** [comment]
@rspezialetti Change applied. I guess is good to merge. Thanks for your feedback!

**Comment by rspezialetti** [comment]
@brunoeducsantos Thanks, we will merge it asap.

**Pull request merged**
